version: '3.8'

services:
  naming-server:
    image: cosmopk/habsat-naming-server:${NAMING_SERVER_VERSION:-master}
    container_name: naming-server
    restart: unless-stopped
    networks:
      - habsat_network

  gateway:
    image: cosmopk/habsat-gateway:${GATEWAY_VERSION:-master}
    container_name: gateway
    restart: unless-stopped
    environment:
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
    networks:
      - habsat_network

  authorization-server:
    image: cosmopk/habsat-authorization-server:${AUTHORIZATION_SERVER_VERSION:-master}
    container_name: authorization-server
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${AUTHORIZATION_SERVER_MONGO_DB}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  email-service:
    image: cosmopk/habsat-email-service:${EMAIL_SERVICE_VERSION:-master}
    container_name: email-service
    restart: unless-stopped
    environment:
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  post-service:
    image: cosmopk/habsat-post-service:${POST_SERVICE_VERSION:-master}
    container_name: post-service
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${POST_SERVICE_MONGO_DB}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  user-service:
    image: cosmopk/habsat-user-service:${USER_SERVICE_VERSION:-master}
    container_name: user-service
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${USER_SERVICE_MONGO_DB}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  flight-service:
    image: cosmopk/habsat-flight-service:${FLIGHT_SERVICE_VERSION:-master}
    container_name: flight-service
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${FLIGHT_SERVICE_MONGO_DB}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

networks:
  habsat_network: null

