version: '3.8'

services:
  naming-server:
    image: cosmopk/habsat-naming-server:${NAMING_SERVER_VERSION:-master}
    container_name: naming-server
    restart: unless-stopped
    networks:
      - habsat_network

  gateway:
    image: cosmopk/habsat-gateway:${GATEWAY_VERSION:-master}
    container_name: gateway
    restart: unless-stopped
    environment:
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    depends_on:
      - naming-server
    networks:
      - habsat_network

  config-server:
    image: cosmopk/habsat-config-server:${CONFIG_SERVER_VERSION:-master}
    container_name: config-server
    restart: unless-stopped
    environment:
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
      CONFIG_PATH: '/config'
    depends_on:
      - naming-server
    volumes:
      - ./.configs:/config
    networks:
      - habsat_network

  authorization-server:
    image: cosmopk/habsat-authorization-server:${AUTHORIZATION_SERVER_VERSION:-master}
    container_name: authorization-server
    restart: unless-stopped
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  email-service:
    image: cosmopk/habsat-email-service:${EMAIL_SERVICE_VERSION:-master}
    container_name: email-service
    restart: unless-stopped
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  post-service:
    image: cosmopk/habsat-post-service:${POST_SERVICE_VERSION:-master}
    container_name: post-service
    restart: unless-stopped
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  user-service:
    image: cosmopk/habsat-user-service:${USER_SERVICE_VERSION:-master}
    container_name: user-service
    restart: unless-stopped
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

  flight-service:
    image: cosmopk/habsat-flight-service:${FLIGHT_SERVICE_VERSION:-master}
    container_name: flight-service
    restart: unless-stopped
    depends_on:
      - naming-server
      - gateway
    networks:
      - habsat_network

networks:
  habsat_network: null

